config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flats do
    collection do
      get :search
    end
  end
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created'
    else
      render :new
    end
  end

  def edit
    @flat = Flat.new
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, notice: 'Restaurant successfully destroyed'
  end

  def search
    @flats = Flat.where("name LIKE '%house%'")
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit <%= @flat.name %></h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :number_of_guests %>
      <%= f.input :price_per_night %>
    </div>

    <div class="form-actions">
      <%= f.submit "Edit Flat", :class => "btn btn-success"%>
    </div>
  <% end %>

</div>

app/views/flats/index.html.erb
<h1>All flats</h1>


<div class="d-flex justify-content-around">
<% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top w-180 h-200" src="https://source.unsplash.com/random" alt="">
      <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= flat.name %></h5>
        <p class="card-text font-weight-italic"><%= flat.description %></p>

        <div class="d-flex justify-content-between">
          <div class="d-flex">
            <i class="material-icons">people</i>
            <p class="card-text"><%= flat.number_of_guests %></p>
          </div>
          <div class="d-flex">
            <i class="material-icons font-size-3">euro_symbol</i>
            <p class="card-text"><%= flat.price_per_night %></p>
          </div>
        </div>

        <%= link_to "More info", flat_path(flat), :class => "btn btn-primary mt-3 font-size" %>
        <%= link_to "Edit", edit_flat_path(flat), :class => "btn btn-warning mt-3" %>
        <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger mt-3" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new Flat</h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :number_of_guests %>
      <%= f.input :price_per_night %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class => "btn btn-success"%>
    </div>
  <% end %>

</div>

app/views/flats/search.html.erb
<h1>Search result</h1>

<div class="d-flex justify-content-around">
<% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top w-180 h-200" src="https://source.unsplash.com/random" alt="">
      <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= flat.name %></h5>
        <p class="card-text font-weight-italic"><%= flat.description %></p>

        <div class="d-flex justify-content-between">
          <div class="d-flex">
            <i class="material-icons">people</i>
            <p class="card-text"><%= flat.number_of_guests %></p>
          </div>
          <div class="d-flex">
            <i class="material-icons font-size-3">euro_symbol</i>
            <p class="card-text"><%= flat.price_per_night %></p>
          </div>
        </div>

        <%= link_to "More info", flat_path(flat), :class => "btn btn-primary mt-3 font-size" %>
        <%= link_to "Edit", edit_flat_path(flat), :class => "btn btn-warning mt-3" %>
        <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger mt-3" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="d-flex">

<div>

  <div class="card bg-light ">
    <h1><%= @flat.name %></h1>
    <h4><%= @flat.address %></h4>
  </div>

  <div class="card">
    <h2>A bit more about this flat...</h2>
    <p><%= @flat.description %></p>
  </div>

</div>

<div>

  <div class="card">
    <h3>Book this place!</h3>
    <a href="#" class="btn btn-success">Book</a>
  </div>

  <div class="card">
    <h2>Details</h2>
    <div class="d-flex">
      <i class="material-icons">people</i>
      <p class="card-text"><%= @flat.number_of_guests %></p>
    </div>
    <div class="d-flex">
      <i class="material-icons font-size-3">euro_symbol</i>
      <p class="card-text"><%= @flat.price_per_night %></p>
    </div>
  </div>

  <div class="card">
    <p>Share</p>
    <i class="material-icons font-size-3">facebook</i>
    <i class="material-icons font-size-3">twitter</i>
    <i class="material-icons font-size-3">pinterest</i>
    <i class="material-icons font-size-3">email</i>
  </div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar mb-3 navbar-light bg-white d-flex justify-content-between">

      <%= link_to "Simple Airbnb", flats_path, :class => "text-decoration-none text-dark font-weight-bold" %>
      <form class="form-inline" id="search-bar">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

        <%= link_to "Search", search_flats_path, :class => "btn btn-outline-success my-2 my-sm-0"%>
        <%= link_to "Add Flat", new_flat_path, :class => "btn btn-outline-primary my-2 my-sm-0 ml-3" %>
      </form>
    </nav>
    <%= yield %>

  </body>
</html>